/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Category {
  id?: number;
  name?: string;
  [k: string]: unknown;
}

import { JSONSchema } from '../../lib/json-schema.base'

export class CategorySchema extends JSONSchema {
  constructor() {
    super({
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        }
      }
    })
  }
}
