/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Order {
  id?: number;
  petId?: number;
  quantity?: number;
  shipDate?: string;
  /**
   * Order Status
   */
  status?: "placed" | "approved" | "delivered";
  complete?: boolean;
  [k: string]: unknown;
}

import { JSONSchema } from '../../lib/json-schema.base'

export class OrderSchema extends JSONSchema {
  constructor() {
    super({
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "petId": {
          "type": "integer"
        },
        "quantity": {
          "type": "integer"
        },
        "shipDate": {
          "type": "string"
        },
        "status": {
          "type": "string",
          "description": "Order Status",
          "enum": [
            "placed",
            "approved",
            "delivered"
          ]
        },
        "complete": {
          "type": "boolean"
        }
      }
    })
  }
}
